### PR TITLE
Fix blog descriptions not showing

### LINKED ISSUE #166: Blog description not showing

### PR DESCRIPTION
**Pull request by qilto**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #166

Test URLs:
- Before: https://main--uhg-surest--hlxsites.hlx.live/blog/
- After: https://blog-description-fix--uhg-surest--hlxsites.hlx.live/blog/

### CODE REVIEW

File: blocks/cards/cards.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ function createBlogCard(blog) {
   blogBody.appendChild(blogLinkWrapper);
   blogBody.appendChild(blogInfo);
   blogBody.appendChild(blogTitle);
-  if (getMetadata('theme').toLowerCase() === 'blog' && getMetadata('template').toLowerCase() === 'no hero') {
+  if (getMetadata('theme').toLowerCase() === 'blog' && document.querySelector('.no-hero')) {
```
Comment (shsteimer) [inline blocks/cards/cards.js:50]: I'm curious why cards would care that there is a hero or not?

I assume the idea here is to show a description on the card on the blog landing page, but not in the related cards on the blogs themselves?

Comment (qilto) [reply blocks/cards/cards.js:50]: Yeah I was just trying to make sure it only showed on the main blog page. I think your suggestion is better.

**Comment by shsteimer** [comment]
WE need to work on the page speed for this. not gonna block that from merging for now, as the current page has same speed performance, but I' created #169 to address.

**Review by shsteimer — APPROVED** [review]
